version: "3.8"
services:
  arizona-perez:
    build: .
    volumes:
      - .:/usr/bakalarka
    stdin_open: true
    tty: true
    command: >
      python3 main.py 
        -I ../webcamCalibration/images/gradient 
        -J ../webcamCalibration/images/clearDay 
        -m ../webcamCalibration/skyMask/mask.jpg 
        -n 1000 -W 720 -H 540 -f0 500 
        -df matlab-flat
        -mJ perez
        -min 10
        -max 240
    working_dir: /usr/bakalarka/src

  arizona-prague:
    build: .
    volumes:
      - .:/usr/bakalarka
    stdin_open: true
    tty: true
    command: >
      python3 main.py 
        -I ../webcamCalibration/images/gradient 
        -J ../webcamCalibration/images/clearDay 
        -m ../webcamCalibration/skyMask/mask.jpg 
        -n 1000 -W 720 -H 540 -f0 500 
        -df matlab-flat
        -mJ prague
        -min 10
        -max 240
    working_dir: /usr/bakalarka/src

  chmu-perez:
    build: .
    volumes:
      - .:/usr/bakalarka
    stdin_open: true
    tty: true
    command: >
      bash -c "
        ./chmucalib.sh ceske_budejovice perez >> chmu-perez-log.txt
        ./chmucalib.sh dukovany perez >> chmu-perez-log.txt
        ./chmucalib.sh holesov perez >> chmu-perez-log.txt
        ./chmucalib.sh olomouc perez >> chmu-perez-log.txt
        ./chmucalib.sh pribyslav perez >> chmu-perez-log.txt
        ./chmucalib.sh polom perez >> chmu-perez-log.txt
        ./chmucalib.sh primda perez >> chmu-perez-log.txt
        ./chmucalib.sh temelin perez >> chmu-perez-log.txt
        ./chmucalib.sh brno perez >> chmu-perez-log.txt
        ./chmucalib.sh nedvezi perez >> chmu-perez-log.txt
      "
    working_dir: /usr/bakalarka/src

  chmu-prague:
    build: .
    volumes:
      - .:/usr/bakalarka
    stdin_open: true
    tty: true
    command: >
      bash -c "
        ./chmucalib.sh ceske_budejovice prague >> chmu-prague-log.txt
        ./chmucalib.sh dukovany prague >> chmu-prague-log.txt
        ./chmucalib.sh holesov prague >> chmu-prague-log.txt
        ./chmucalib.sh olomouc prague >> chmu-prague-log.txt
        ./chmucalib.sh pribyslav prague >> chmu-prague-log.txt
        ./chmucalib.sh polom prague >> chmu-prague-log.txt
        ./chmucalib.sh primda prague >> chmu-prague-log.txt
        ./chmucalib.sh temelin prague >> chmu-prague-log.txt
        ./chmucalib.sh brno prague >> chmu-prague-log.txt
        ./chmucalib.sh nedvezi prague >> chmu-prague-log.txt
      "
    working_dir: /usr/bakalarka/src

  chmu-perez-clean:
    build: .
    volumes:
      - .:/usr/bakalarka
    stdin_open: true
    tty: true
    command: >
      bash -c "
        ./chmucalib-clean.sh ceske_budejovice perez >> chmu-perez-clean-log.txt
        ./chmucalib-clean.sh dukovany perez >> chmu-perez-clean-log.txt
        ./chmucalib-clean.sh holesov perez >> chmu-perez-clean-log.txt
        ./chmucalib-clean.sh olomouc perez >> chmu-perez-clean-log.txt
        ./chmucalib-clean.sh pribyslav perez >> chmu-perez-clean-log.txt
        ./chmucalib-clean.sh polom perez >> chmu-perez-clean-log.txt
        ./chmucalib-clean.sh primda perez >> chmu-perez-clean-log.txt
        ./chmucalib-clean.sh temelin perez >> chmu-perez-clean-log.txt
        ./chmucalib-clean.sh brno perez >> chmu-perez-clean-log.txt
        ./chmucalib-clean.sh nedvezi perez >> chmu-perez-clean-log.txt
      "
    working_dir: /usr/bakalarka/src

  chmu-prague-clean:
    build: .
    volumes:
      - .:/usr/bakalarka
    stdin_open: true
    tty: true
    command: >
      bash -c "
        ./chmucalib-clean.sh ceske_budejovice prague >> chmu-prague-clean-log.txt
        ./chmucalib-clean.sh dukovany prague >> chmu-prague-clean-log.txt
        ./chmucalib-clean.sh holesov prague >> chmu-prague-clean-log.txt
        ./chmucalib-clean.sh olomouc prague >> chmu-prague-clean-log.txt
        ./chmucalib-clean.sh pribyslav prague >> chmu-prague-clean-log.txt
        ./chmucalib-clean.sh polom prague >> chmu-prague-clean-log.txt
        ./chmucalib-clean.sh primda prague >> chmu-prague-clean-log.txt
        ./chmucalib-clean.sh temelin prague >> chmu-prague-clean-log.txt
        ./chmucalib-clean.sh brno prague >> chmu-prague-clean-log.txt
        ./chmucalib-clean.sh nedvezi prague >> chmu-prague-clean-log.txt
      "
    working_dir: /usr/bakalarka/src

  bash:
    build: .
    container_name: bakalarka
    volumes:
      - .:/usr/bakalarka
    stdin_open: true
    tty: true
    command: bash
    working_dir: /usr/bakalarka/src
